name: Build & Publish to docs (GitHub Pages)

on:
  push:
    branches: [ main ]
    # Prevent infinite loops: don't rerun when only /docs changes are pushed by this job
    paths-ignore:
      - 'docs/**'

permissions:
  contents: write  # needed to push the updated /docs back to main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci || npm install

      - name: Build
        run: npm run build
        env:
          CI: true

      - name: Publish to docs/
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r dist/* docs/
          cp docs/index.html docs/404.html   # SPA fallback for deep links
          touch docs/.nojekyll               # disable Jekyll processing

      # Commit only if /docs actually changed
      - name: Commit & push docs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git diff --cached --quiet && echo "No changes in docs — skip commit." || git commit -m "CI: build & publish to docs"
          git push
